# Generated by Django 6.0.1 on 2026-02-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ide_code',
            field=models.TextField(blank=True, default='// Start coding...'),
        ),
        migrations.AddField(
            model_name='session',
            name='ide_language',
            field=models.CharField(default='javascript', max_length=50),
        ),
        migrations.AddField(
            model_name='session',
            name='whiteboard_state',
            field=models.TextField(blank=True, default=''),
        ),
    ]
