# Generated by Django 6.0.1 on 2026-02-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_to_learn', models.CharField(help_text='Topic the user wants to learn', max_length=255)),
                ('topic_to_teach', models.CharField(blank=True, default='', help_text='Topic the user can teach in exchange (optional)', max_length=255)),
                ('ok_with_just_learning', models.BooleanField(default=False, help_text='User is okay with just learning (paying credits)')),
                ('bounty_enabled', models.BooleanField(default=False, help_text='User is willing to pay extra credits as bounty')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether this request has been fulfilled')),
            ],
            options={
                'verbose_name': 'learning request',
                'verbose_name_plural': 'learning requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
